[project]
name="llm-engineering"
version="1.0.0"
python-version=">3.12"
dependencies=[
    "python-dotenv",
    "openai",
    "beautifulsoup4",
    "requests",
    "langchain",
    "langchain-openai",
    "langchain-chroma",
    "langchain-text-splitters",
    "langchain-huggingface",
    "gradio"
]